# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `config`: specifies the module configuration.
# `pathvars:` helps you re-wire where the module places files.
module module_geo_boundaries:
    pathvars:
        # Redirect specific module results (outputs)
        shapes="results/outputs/shapes.parquet",
        # Redirect module intermediate files
        logs="resources/geo_boundaries/logs",
        resources="resources/geo_boundaries/resources",
        results="resources/geo_boundaries/results",
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_geo_boundaries"]


# Add a prefix to all module rules, to avoid naming conflicts.
use rule * from module_geo_boundaries as geo_boundaries_module_*


# Request something from the module
rule all:
    default_target: True
    input:
        "results/outputs/shapes.parquet",
    message:
        "A generic test case for this module."
