$schema: "https://json-schema.org/draft/2020-12/schema"

$defs:
  epsgCode:
    anyOf:
      - type: string
        pattern: '^(?:[eE][pP][sS][gG]):\d{4,5}$'
      - type: integer
        minimum: 1000
        maximum: 99999

description: "Schema for user-provided configuration files."
type: object
properties:
  crs:
    description: CRS codes (i.e., 'epsg:3035', 'EPSG:4326', 8857).
    type: object
    properties:
      projected:
        description: "Projected CRS code (for area and length calculation)."
        allOf:
          - $ref: '#/$defs/epsgCode'
      geographic:
        description: "Geographic CRS code (for latitude / longitude positioning)."
        allOf:
          - $ref: '#/$defs/epsgCode'
    required:
      - projected
      - geographic
    additionalProperties: False
  countries:
    description: >
      Dictionary of countries with each country code as the key.
      Country code must be in ISO alpha-3 format (e.g., MEX, CHN, DEU).
    type: object
    patternProperties:
      "^[A-Z]{3}$":  # Keys must be exactly three uppercase letters
        type: object
        properties:
          subtype:
            description: >
              "Regional aggregation to gather (e.g., '0', '1', or '2' for GADM). Names vary per dataset."
            type: string
          source:
            description: |
              Dataset to use as source.
            type: string
            enum: ["overture", "gadm", "nuts"]
          resolution:
            description: "Resolution for NUTS source (required if source is 'nuts')."
            type: string
            pattern: "^[0-9]{2}M$"
          year:
            description: "Year for NUTS source (required if source is 'nuts')."
            type: integer
          extra_eez:
            description: >
              Optional. Additional EEZ zones to append to this country.
            default: []
            anyOf:
              - type: integer
              - type: array
                items:
                  type: integer
        required:
          - subtype
          - source
        additionalProperties: false
        allOf:
          - if:
              properties:
                source:
                  enum: ["nuts"]
            then:
              required:
                - resolution
                - year
          - else:
              not:
                required:
                  - resolution
                  - year
    minProperties: 1
    additionalProperties: false
  overture_release:
    description: |
      Overture data release to use. Two options are possible:
      - A specific release string in the form of 'yyyy-mm-dd.x'.
      - A request for the latest release in the form of 'latest'.
    type: string
    pattern: "^(?:latest|(?:\\d{4})-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])\\.\\d+)$"
  voronoi_eez:
    description: >
      Optional configuration for the Voronoi EEZ splitting algorithm.
    type: object
    required:
      - enabled
      - sample_spacing
    properties:
      enabled:
        description: Activation of the splitting algorithm.
        type: boolean
        default: false
      sample_spacing:
        description: >
          Distance between sample points for shorelines.
          Higher for finer splits at the cost of slower processing.
          Matches the unit of the projected CRS.
        type: integer
        default: 10000
        minimum: 1
required:
  - countries
  - crs
additionalProperties: false
