# A minimal example of how to configure this module

# Default global settings across scenarios
voronoi_eez:
  enabled: True
  sample_spacing: 10000 # sample every 10 km
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"

# At least one scenario.
# We include four cases as examples.
scenarios:
  mixed_example:
    # Assorted countries
    countries:
      DNK:
        subtype: "1"
        source: "nuts"
        resolution: 01M
        year: 2024
      GBR:
        subtype: "country"
        source: "overture"
      NLD:
        subtype: 0
        source: "geoboundaries"
        release_type: "gbOpen"
      BEL:
        subtype: 1
        source: "geoboundaries"
        release_type: "gbOpen"
      CHE:
        subtype: "country"
        source: "overture"
      ESP:
        subtype: "2"
        source: "nuts"
        resolution: 01M
        year: 2024
        extra_eez: 8364
  china_national:
    # Large country at national level
    # China has contested borders, which will be removed by the module
    voronoi_eez:
      enabled: False
      sample_spacing: 10000
    countries:
      "CHN":
        subtype: "country"
        source: "overture"
  USA_states:
    # Example of regional disaggregation of a large country crossing the antimeridean.
    # USA has multiple marine zones, which can be appended as extras
    countries:
      "USA":
        subtype: "1"
        source: "gadm"
        extra_eez: [8463, 8453]
  europe_regions:
    # A large continental example.
    # Europe at regional resolution.
    crs:
      projected: "epsg:3035"
      geographic: "epsg:4326"
    countries:
      "ALB":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "AUT":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "BEL":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "BGR":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "BIH":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "CHE":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "CYP":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "CZE":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "DEU":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "DNK":
        subtype: "1"
        source: "nuts"
        resolution: 01M
        year: 2024
      "ESP":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
        extra_eez: 8364
      "EST":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "FIN":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "FRA":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "GBR":
        subtype: "region"
        source: "overture"
      "GGY":
        subtype: "0"
        source: "geoboundaries"
        release_type: "gbOpen"
      "GRC":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "HRV":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "HUN":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "IMN":
        subtype: "0"
        source: "geoboundaries"
        release_type: "gbOpen"
      "IRL":
        subtype: "region"
        source: "overture"
      "ITA":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "LTU":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "LUX":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "LVA":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "MKD":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "MNE":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "NLD":
        subtype: "region"
        source: "overture"
      "NOR":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "POL":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "PRT":
        subtype: "1"
        source: "nuts"
        resolution: 01M
        year: 2024
        extra_eez: [8361, 8363]
      "ROU":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "SRB":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "SVK":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "SVN":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "SWE":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
      "XKX":
        subtype: "1"
        source: "geoboundaries"
        release_type: "gbOpen"
