# Example of regional disaggregation of a large country
# USA has multiple marine zones, which can be appended as extras
overture_release: "latest"
voronoi_eez:
  enabled: True
  sample_spacing: 10000 # sample every 10 km
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
countries:
  "USA":
    subtype: "1"
    source: "gadm"
    extra_eez: [8463, 8453]
